################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../HAL_Driver/Src/stm32f7xx_hal.c \
../HAL_Driver/Src/stm32f7xx_hal_adc.c \
../HAL_Driver/Src/stm32f7xx_hal_adc_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_can.c \
../HAL_Driver/Src/stm32f7xx_hal_cec.c \
../HAL_Driver/Src/stm32f7xx_hal_cortex.c \
../HAL_Driver/Src/stm32f7xx_hal_crc.c \
../HAL_Driver/Src/stm32f7xx_hal_crc_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_cryp.c \
../HAL_Driver/Src/stm32f7xx_hal_cryp_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_dac.c \
../HAL_Driver/Src/stm32f7xx_hal_dac_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_dcmi.c \
../HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_dfsdm.c \
../HAL_Driver/Src/stm32f7xx_hal_dma.c \
../HAL_Driver/Src/stm32f7xx_hal_dma2d.c \
../HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_dsi.c \
../HAL_Driver/Src/stm32f7xx_hal_eth.c \
../HAL_Driver/Src/stm32f7xx_hal_flash.c \
../HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_gpio.c \
../HAL_Driver/Src/stm32f7xx_hal_hash.c \
../HAL_Driver/Src/stm32f7xx_hal_hash_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_hcd.c \
../HAL_Driver/Src/stm32f7xx_hal_i2c.c \
../HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_i2s.c \
../HAL_Driver/Src/stm32f7xx_hal_irda.c \
../HAL_Driver/Src/stm32f7xx_hal_iwdg.c \
../HAL_Driver/Src/stm32f7xx_hal_jpeg.c \
../HAL_Driver/Src/stm32f7xx_hal_lptim.c \
../HAL_Driver/Src/stm32f7xx_hal_ltdc.c \
../HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_mdios.c \
../HAL_Driver/Src/stm32f7xx_hal_mmc.c \
../HAL_Driver/Src/stm32f7xx_hal_nand.c \
../HAL_Driver/Src/stm32f7xx_hal_nor.c \
../HAL_Driver/Src/stm32f7xx_hal_pcd.c \
../HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_pwr.c \
../HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_qspi.c \
../HAL_Driver/Src/stm32f7xx_hal_rcc.c \
../HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_rng.c \
../HAL_Driver/Src/stm32f7xx_hal_rtc.c \
../HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_sai.c \
../HAL_Driver/Src/stm32f7xx_hal_sai_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_sd.c \
../HAL_Driver/Src/stm32f7xx_hal_sdram.c \
../HAL_Driver/Src/stm32f7xx_hal_smartcard.c \
../HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_smbus.c \
../HAL_Driver/Src/stm32f7xx_hal_spdifrx.c \
../HAL_Driver/Src/stm32f7xx_hal_spi.c \
../HAL_Driver/Src/stm32f7xx_hal_sram.c \
../HAL_Driver/Src/stm32f7xx_hal_tim.c \
../HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
../HAL_Driver/Src/stm32f7xx_hal_uart.c \
../HAL_Driver/Src/stm32f7xx_hal_usart.c \
../HAL_Driver/Src/stm32f7xx_hal_wwdg.c \
../HAL_Driver/Src/stm32f7xx_ll_adc.c \
../HAL_Driver/Src/stm32f7xx_ll_crc.c \
../HAL_Driver/Src/stm32f7xx_ll_dac.c \
../HAL_Driver/Src/stm32f7xx_ll_dma.c \
../HAL_Driver/Src/stm32f7xx_ll_dma2d.c \
../HAL_Driver/Src/stm32f7xx_ll_exti.c \
../HAL_Driver/Src/stm32f7xx_ll_fmc.c \
../HAL_Driver/Src/stm32f7xx_ll_gpio.c \
../HAL_Driver/Src/stm32f7xx_ll_i2c.c \
../HAL_Driver/Src/stm32f7xx_ll_lptim.c \
../HAL_Driver/Src/stm32f7xx_ll_pwr.c \
../HAL_Driver/Src/stm32f7xx_ll_rcc.c \
../HAL_Driver/Src/stm32f7xx_ll_rng.c \
../HAL_Driver/Src/stm32f7xx_ll_rtc.c \
../HAL_Driver/Src/stm32f7xx_ll_sdmmc.c \
../HAL_Driver/Src/stm32f7xx_ll_spi.c \
../HAL_Driver/Src/stm32f7xx_ll_tim.c \
../HAL_Driver/Src/stm32f7xx_ll_usart.c \
../HAL_Driver/Src/stm32f7xx_ll_usb.c \
../HAL_Driver/Src/stm32f7xx_ll_utils.c 

OBJS += \
./HAL_Driver/Src/stm32f7xx_hal.o \
./HAL_Driver/Src/stm32f7xx_hal_adc.o \
./HAL_Driver/Src/stm32f7xx_hal_adc_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_can.o \
./HAL_Driver/Src/stm32f7xx_hal_cec.o \
./HAL_Driver/Src/stm32f7xx_hal_cortex.o \
./HAL_Driver/Src/stm32f7xx_hal_crc.o \
./HAL_Driver/Src/stm32f7xx_hal_crc_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_cryp.o \
./HAL_Driver/Src/stm32f7xx_hal_cryp_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_dac.o \
./HAL_Driver/Src/stm32f7xx_hal_dac_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_dcmi.o \
./HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_dfsdm.o \
./HAL_Driver/Src/stm32f7xx_hal_dma.o \
./HAL_Driver/Src/stm32f7xx_hal_dma2d.o \
./HAL_Driver/Src/stm32f7xx_hal_dma_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_dsi.o \
./HAL_Driver/Src/stm32f7xx_hal_eth.o \
./HAL_Driver/Src/stm32f7xx_hal_flash.o \
./HAL_Driver/Src/stm32f7xx_hal_flash_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_gpio.o \
./HAL_Driver/Src/stm32f7xx_hal_hash.o \
./HAL_Driver/Src/stm32f7xx_hal_hash_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_hcd.o \
./HAL_Driver/Src/stm32f7xx_hal_i2c.o \
./HAL_Driver/Src/stm32f7xx_hal_i2c_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_i2s.o \
./HAL_Driver/Src/stm32f7xx_hal_irda.o \
./HAL_Driver/Src/stm32f7xx_hal_iwdg.o \
./HAL_Driver/Src/stm32f7xx_hal_jpeg.o \
./HAL_Driver/Src/stm32f7xx_hal_lptim.o \
./HAL_Driver/Src/stm32f7xx_hal_ltdc.o \
./HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_mdios.o \
./HAL_Driver/Src/stm32f7xx_hal_mmc.o \
./HAL_Driver/Src/stm32f7xx_hal_nand.o \
./HAL_Driver/Src/stm32f7xx_hal_nor.o \
./HAL_Driver/Src/stm32f7xx_hal_pcd.o \
./HAL_Driver/Src/stm32f7xx_hal_pcd_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_pwr.o \
./HAL_Driver/Src/stm32f7xx_hal_pwr_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_qspi.o \
./HAL_Driver/Src/stm32f7xx_hal_rcc.o \
./HAL_Driver/Src/stm32f7xx_hal_rcc_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_rng.o \
./HAL_Driver/Src/stm32f7xx_hal_rtc.o \
./HAL_Driver/Src/stm32f7xx_hal_rtc_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_sai.o \
./HAL_Driver/Src/stm32f7xx_hal_sai_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_sd.o \
./HAL_Driver/Src/stm32f7xx_hal_sdram.o \
./HAL_Driver/Src/stm32f7xx_hal_smartcard.o \
./HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_smbus.o \
./HAL_Driver/Src/stm32f7xx_hal_spdifrx.o \
./HAL_Driver/Src/stm32f7xx_hal_spi.o \
./HAL_Driver/Src/stm32f7xx_hal_sram.o \
./HAL_Driver/Src/stm32f7xx_hal_tim.o \
./HAL_Driver/Src/stm32f7xx_hal_tim_ex.o \
./HAL_Driver/Src/stm32f7xx_hal_uart.o \
./HAL_Driver/Src/stm32f7xx_hal_usart.o \
./HAL_Driver/Src/stm32f7xx_hal_wwdg.o \
./HAL_Driver/Src/stm32f7xx_ll_adc.o \
./HAL_Driver/Src/stm32f7xx_ll_crc.o \
./HAL_Driver/Src/stm32f7xx_ll_dac.o \
./HAL_Driver/Src/stm32f7xx_ll_dma.o \
./HAL_Driver/Src/stm32f7xx_ll_dma2d.o \
./HAL_Driver/Src/stm32f7xx_ll_exti.o \
./HAL_Driver/Src/stm32f7xx_ll_fmc.o \
./HAL_Driver/Src/stm32f7xx_ll_gpio.o \
./HAL_Driver/Src/stm32f7xx_ll_i2c.o \
./HAL_Driver/Src/stm32f7xx_ll_lptim.o \
./HAL_Driver/Src/stm32f7xx_ll_pwr.o \
./HAL_Driver/Src/stm32f7xx_ll_rcc.o \
./HAL_Driver/Src/stm32f7xx_ll_rng.o \
./HAL_Driver/Src/stm32f7xx_ll_rtc.o \
./HAL_Driver/Src/stm32f7xx_ll_sdmmc.o \
./HAL_Driver/Src/stm32f7xx_ll_spi.o \
./HAL_Driver/Src/stm32f7xx_ll_tim.o \
./HAL_Driver/Src/stm32f7xx_ll_usart.o \
./HAL_Driver/Src/stm32f7xx_ll_usb.o \
./HAL_Driver/Src/stm32f7xx_ll_utils.o 

C_DEPS += \
./HAL_Driver/Src/stm32f7xx_hal.d \
./HAL_Driver/Src/stm32f7xx_hal_adc.d \
./HAL_Driver/Src/stm32f7xx_hal_adc_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_can.d \
./HAL_Driver/Src/stm32f7xx_hal_cec.d \
./HAL_Driver/Src/stm32f7xx_hal_cortex.d \
./HAL_Driver/Src/stm32f7xx_hal_crc.d \
./HAL_Driver/Src/stm32f7xx_hal_crc_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_cryp.d \
./HAL_Driver/Src/stm32f7xx_hal_cryp_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_dac.d \
./HAL_Driver/Src/stm32f7xx_hal_dac_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_dcmi.d \
./HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_dfsdm.d \
./HAL_Driver/Src/stm32f7xx_hal_dma.d \
./HAL_Driver/Src/stm32f7xx_hal_dma2d.d \
./HAL_Driver/Src/stm32f7xx_hal_dma_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_dsi.d \
./HAL_Driver/Src/stm32f7xx_hal_eth.d \
./HAL_Driver/Src/stm32f7xx_hal_flash.d \
./HAL_Driver/Src/stm32f7xx_hal_flash_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_gpio.d \
./HAL_Driver/Src/stm32f7xx_hal_hash.d \
./HAL_Driver/Src/stm32f7xx_hal_hash_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_hcd.d \
./HAL_Driver/Src/stm32f7xx_hal_i2c.d \
./HAL_Driver/Src/stm32f7xx_hal_i2c_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_i2s.d \
./HAL_Driver/Src/stm32f7xx_hal_irda.d \
./HAL_Driver/Src/stm32f7xx_hal_iwdg.d \
./HAL_Driver/Src/stm32f7xx_hal_jpeg.d \
./HAL_Driver/Src/stm32f7xx_hal_lptim.d \
./HAL_Driver/Src/stm32f7xx_hal_ltdc.d \
./HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_mdios.d \
./HAL_Driver/Src/stm32f7xx_hal_mmc.d \
./HAL_Driver/Src/stm32f7xx_hal_nand.d \
./HAL_Driver/Src/stm32f7xx_hal_nor.d \
./HAL_Driver/Src/stm32f7xx_hal_pcd.d \
./HAL_Driver/Src/stm32f7xx_hal_pcd_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_pwr.d \
./HAL_Driver/Src/stm32f7xx_hal_pwr_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_qspi.d \
./HAL_Driver/Src/stm32f7xx_hal_rcc.d \
./HAL_Driver/Src/stm32f7xx_hal_rcc_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_rng.d \
./HAL_Driver/Src/stm32f7xx_hal_rtc.d \
./HAL_Driver/Src/stm32f7xx_hal_rtc_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_sai.d \
./HAL_Driver/Src/stm32f7xx_hal_sai_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_sd.d \
./HAL_Driver/Src/stm32f7xx_hal_sdram.d \
./HAL_Driver/Src/stm32f7xx_hal_smartcard.d \
./HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_smbus.d \
./HAL_Driver/Src/stm32f7xx_hal_spdifrx.d \
./HAL_Driver/Src/stm32f7xx_hal_spi.d \
./HAL_Driver/Src/stm32f7xx_hal_sram.d \
./HAL_Driver/Src/stm32f7xx_hal_tim.d \
./HAL_Driver/Src/stm32f7xx_hal_tim_ex.d \
./HAL_Driver/Src/stm32f7xx_hal_uart.d \
./HAL_Driver/Src/stm32f7xx_hal_usart.d \
./HAL_Driver/Src/stm32f7xx_hal_wwdg.d \
./HAL_Driver/Src/stm32f7xx_ll_adc.d \
./HAL_Driver/Src/stm32f7xx_ll_crc.d \
./HAL_Driver/Src/stm32f7xx_ll_dac.d \
./HAL_Driver/Src/stm32f7xx_ll_dma.d \
./HAL_Driver/Src/stm32f7xx_ll_dma2d.d \
./HAL_Driver/Src/stm32f7xx_ll_exti.d \
./HAL_Driver/Src/stm32f7xx_ll_fmc.d \
./HAL_Driver/Src/stm32f7xx_ll_gpio.d \
./HAL_Driver/Src/stm32f7xx_ll_i2c.d \
./HAL_Driver/Src/stm32f7xx_ll_lptim.d \
./HAL_Driver/Src/stm32f7xx_ll_pwr.d \
./HAL_Driver/Src/stm32f7xx_ll_rcc.d \
./HAL_Driver/Src/stm32f7xx_ll_rng.d \
./HAL_Driver/Src/stm32f7xx_ll_rtc.d \
./HAL_Driver/Src/stm32f7xx_ll_sdmmc.d \
./HAL_Driver/Src/stm32f7xx_ll_spi.d \
./HAL_Driver/Src/stm32f7xx_ll_tim.d \
./HAL_Driver/Src/stm32f7xx_ll_usart.d \
./HAL_Driver/Src/stm32f7xx_ll_usb.d \
./HAL_Driver/Src/stm32f7xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
HAL_Driver/Src/%.o: ../HAL_Driver/Src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DSTM32 -DSTM32F7 -DSTM32F769NIHx -DSTM32F769I_DISCO -DDEBUG -DSTM32F769xx -DUSE_HAL_DRIVER -DINCLUDE_FATFS -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/ampire480272" -I"/home/aet/eclipse-workspace/ArmEchoServer/HAL_Driver/Inc" -I"/home/aet/eclipse-workspace/ArmEchoServer/inc" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/s5k5cag" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/mfxstm32l152" -I"/home/aet/eclipse-workspace/ArmEchoServer/CMSIS/device" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/st7735" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/rk043fn48h" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/ov9655" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/otm8009a" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/Common" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/FatFs/src" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/apps/httpd" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/test/fuzz" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include/lwip" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/system/arch" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include/lwip/priv" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/test/unit/udp" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/test/unit/mdns" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/stmpe811" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Fonts" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/test/unit/core" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/exc7200" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include/netif/ppp/polarssl" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/adv7533" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include/netif" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/ampire640480" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/STM32F769I-Discovery" -I"/home/aet/eclipse-workspace/ArmEchoServer/CMSIS/core" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include/netif/ppp" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include/posix" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/test/unit/tcp" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/n25q512a" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/apps/snmp" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/n25q128a" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/ts3510" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/test/unit/ip4" -I"/home/aet/eclipse-workspace/ArmEchoServer/HAL_Driver/Inc/Legacy" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/test/unit/etharp" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/test/unit" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/wm8994" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include/lwip/prot" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/ft5336" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/ft6x06" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/doc/doxygen" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include/lwip/apps" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/st7789h2" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Log" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/test/unit/dhcp" -I"/home/aet/eclipse-workspace/ArmEchoServer/Utilities/Components/mx25l512" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/src/include" -I"/home/aet/eclipse-workspace/ArmEchoServer/Middlewares/Third_Party/LwIP/system" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


